/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_affiche (void);
GtkWidget* create_fenetre_modif (void);
GtkWidget* create_tache2 (void);
